

###
GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET http://localhost:80/api/item?id=99
Accept: application/json

###
### 注册
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "che_shuai@massclouds.com",
  "password": "123456",
  "registerAsAdmin": "true"
}

### 登录

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "che_shuai@massclouds.com",
  "password": "111111",
  "deviceInfo": {
    "deviceId": "htc",
    "deviceType": "DEVICE_TYPE_ANDROID"

  }
}

###  registrationConfirmation  注册确认
GET {{host}}/api/auth/registrationConfirmation?token=899cd142-f204-4046-9005-138bf63f1d2a

### 使用令牌登录成功
GET {{host}}/api/user/me
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTkwNzQxNjUwLCJleHAiOjE1OTA3NDI1NTB9.85-RUYUA9EJXSGDoBPqNUQaTm21_u9Tg8V41ceJSYFqMjI-437g93zfrN0fChtIPVnivHpHB6xPxoZyXFbivZw

###
POST {{host}}/api/auth/password/resetlink
Content-Type: application/json

{
  "email": "che_shuai@massclouds.com"
}

###
POST {{host}}/api/auth/password/reset
Content-Type: application/json

{
"password":"111111",
"confirmPassword":"111111",
"token": "74afd7f7-2772-422c-93b1-8ffbe82fc721"
}

### 刷新当前用户的token
POST {{host}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "ff2a1198-181e-430e-ba8b-b21ec55b25c9"
}


### 测试接口
GET {{host}}/api/security/test
Accept: application/json
Cookie: JSESSIONID=C2E7D6491E6A9CCD57BFCC7F57493536
token=3D74afd7f7-2772-422c-93=b1-8ffbe82fc721"

###
