#spring.datasource:
#  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
##  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
##spring.datasource.url: jdbc:h2:file:./camunda-h2-database
##shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
#  username: sa
#  password: sa
#spring.h2.console.enabled: true
# camunda-workflow:setting
camunda:
  datasource:
#    driverClassName: org.postgresql.Driver
    # h2, mysql, mariadb, oracle, postgres, mssql, db2
    schema-name: camunda
    url: jdbc:h2:./workflow-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    filter:
      create: All tasks
    # web application setting
    webapp:
      application-path: '/'
    process-engine-name: 'Appfabric'

# Spring-data-jap:setting
spring:
  jpa:
    hibernate:
      ddl-auto: create
      hbm2ddl.auto: create
    show-sql: true
    generate-ddl: true

  jersey:
    application-path: '/rest'

# port
server.port: 8080
#application
#
domain:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.9.26:5432/domaindata
    username: postgres
    password: postgres
    configuration.maximum-pool-size: 30

#camunda.bpm.webapp.application-path: '/'
#spring.jersey.application-path: '/rest'